### ISSUE TITLE
Package versions of libraries

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/utils#38]
- [x] Currently, we have a history of multiple older versions of libraries to maintain for adapter, utils, message-rosa, and dao. We need to decide whether to maintain these versions or delete them.
- [ ] We also need to follow a fixed documented convention while building releases for all these libraries. There should be different release tags based on development and production code.
- [x] We may add a feature to our GitHub actions to build these versions based on which branch code is pushed to. If we push to `development` a staging release should be built with the corresponding tag and if we push to `master` a production build with the proper release tag should be built.
- [ ] We need to decide whether the versions of all the libraries should remain similar to each other or they may be different based on individual code updates. If the versions are kept different we need some way to document which version of a particular library is stable with which version of another library. For example, version `1.2.0` of the adapter may be stable with version `1.2.4` utils but not with `1.2.5`.

**Comment by pankajjangid05** [comment]
Deployed code on stagging with below release tags and package name: 

1. [Utils](https://github.com/samagra-comms/utils/packages/1414769) : Package Name - 2.2.0-SNAPSHOT
2. [Message-Rosa](https://github.com/samagra-comms/message-rosa/packages/1390568) : Package Name - 2.2.0-SNAPSHOT
3. [Dao](https://github.com/samagra-comms/dao/packages/1369876) : Package Name - 2.2.0-SNAPSHOT
4. [Adapter](https://github.com/samagra-comms/adapter/packages/1419676) : Package Name - 2.2.0-SNAPSHOT
5. [Inbound](https://github.com/samagra-comms/inbound/releases/tag/v2.2.0-SNAPSHOT) : Release Tag - v2.2.0-SNAPSHOT
6. [Orchestrator](https://github.com/samagra-comms/orchestrator/releases/tag/v2.2.0-SNAPSHOT) : Release Tag - v2.2.0-SNAPSHOT
7. [Transformer](https://github.com/samagra-comms/transformer/releases/tag/v2.2.0-SNAPSHOT) : Release Tag - v2.2.0-SNAPSHOT
8. [Broadcast-Transformer](https://github.com/samagra-comms/broadcast-transformer/releases/tag/v2.2.0-SNAPSHOT) : Release Tag - v2.2.0-SNAPSHOT
9. [Outbound](https://github.com/samagra-comms/outbound/releases/tag/v2.2.0-SNAPSHOT) : Release Tag - v2.2.0-SNAPSHOT

These are only for stagging deployment.

**Comment by chinmoy12c** [comment]
1. We will keep the history of those builds, but we will not support those versions and tag those as deprecated.
4. The libraries would all have the same version to make it easier to manage versions.

**Comment by susheelvar** [comment]
@RyanWalker277 to automatic build and deployment of images on development branch.

**Comment by karntrehan** [comment]
PR raised. Reviewed by @chinmoy12c. To be merged and tested.

**Comment by geeky-abhishek** [comment]
It will be closed by today @RyanWalker277

**Comment by RyanWalker277** [comment]
Hey @pankajjangid05 @chinmoy12c linking the Pull Requests for the rest of the packages. Please review

Utils - https://github.com/samagra-comms/utils/pull/50
Message-rosa - https://github.com/samagra-comms/message-rosa/pull/26
Dao - https://github.com/samagra-comms/dao/pull/13
Adapter - https://github.com/samagra-comms/adapter/pull/44
