### ISSUE TITLE
Update transaction layer search by name handling

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/utils#59]
Due to changes in search API [here](https://github.com/samagra-comms/uci-apis/pull/177) transaction layer needs to update search by name handling.

**Comment by pankajjangid05** [comment]
Hey @chinmoy12c 

Please review this PR: https://github.com/samagra-comms/utils/pull/61

**Comment by chinmoy12c** [comment]
PR is merged. To be deployed on staging.
